name: release

on:
  push:
    tags:
    - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Git Sumbodule Update
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: .github/bin/dist-pack.sh
    - run: .github/bin/dist-github-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
